FROM mcr.microsoft.com/dotnet/sdk:5.0 as build
WORKDIR /app

COPY . .
RUN dotnet restore

FROM build AS publish
RUN dotnet publish Contoso.BackOffice.UI.csproj -c Release -o out

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/out/wwwroot .